services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.3.10
    restart: on-failure
    environment:
      CLICKHOUSE_USER: uptrace
      CLICKHOUSE_PASSWORD: uptrace
      CLICKHOUSE_DB: uptrace
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:8123/ping"]
      interval: 1s
      timeout: 1s
      retries: 30
    volumes:
      - ch_data:/var/lib/clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
  postgres:
    image: postgres:17-alpine
    restart: on-failure
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: uptrace
      POSTGRES_PASSWORD: uptrace
      POSTGRES_DB: uptrace
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U uptrace -d uptrace"]
      interval: 1s
      timeout: 1s
      retries: 30
    volumes:
      - "pg_data3:/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
  redis:
    image: redis:6.2.2-alpine
    restart: on-failure
  uptrace:
    image: "uptrace/uptrace:2.0.2"
    restart: on-failure
    volumes:
      - ./uptrace.yml:/etc/uptrace/config.yml
      - ./certs/server.crt:/etc/uptrace/server.crt
      - ./certs/server.key:/etc/uptrace/server.key
    #environment:
    #  - DEBUG=2
    ports:
      - "4317"
      - "80"
    depends_on:
      - clickhouse
      - postgres
      # Nginx como proxy reverso
  nginx:
    image: nginx:alpine
    restart: on-failure
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS (se usar SSL)
      - "4317:4317" # gRPC OTLP
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # Se usar SSL:
      - ./certs:/etc/nginx/ssl:ro
    depends_on:
      - uptrace
    networks:
      default:
volumes:
  ch_data:
  pg_data3:
  # prometheus_data:
  # mailpit_data:

networks:
  default:
    driver: bridge
